version: '3.8'

services:
  postgres:
    image: postgres:lastest
    volumes:
      - postgres_data:var/lib/postgressql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork

  backend:
    
    build: 
      context: ./backend
      dockerfile: Dockerfile

    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: sqlite:///./meubanco.db
    
    ports:
      - "8000: 8000"

    #depends_on:
    #  - 
    
    networks:
      - mynetwork
  frontend:

networks:
    mynetwork:


#volumes: #fazer com que cosnigo olhar o path e criar um arquivo aqui
  #postgres_data: